global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'league-of-star-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'league-of-star-api-1:8080'
          - 'league-of-star-api-2:8080'
