services:
  mysql:
    image: mysql:8.0
    container_name: league-of-star-mysql
    networks:
      - league-of-star-local
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: league_of_star
      MYSQL_USER: league_of_star
      MYSQL_PASSWORD: league_of_star1234
      TZ: Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7-alpine
    container_name: league-of-star-redis
    networks:
      - league-of-star-local
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  mysql-data:

networks:
  league-of-star-local:
    name: league-of-star-local
