// 실행 모듈: Spring Boot 플러그인 적용 → bootJar 생성
apply plugin: 'org.springframework.boot'

dependencies {
	implementation project(':smite-core')
	implementation project(':smite-infra-redis')
	testImplementation testFixtures(project(':smite-infra-redis'))

	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

	runtimeOnly 'com.mysql:mysql-connector-j'

	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	runtimeOnly 'io.micrometer:micrometer-registry-prometheus'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.testcontainers:junit-jupiter'
	testImplementation 'com.redis:testcontainers-redis'
	testRuntimeOnly 'com.h2database:h2'
}
