plugins {
	id 'com.epages.restdocs-api-spec' version '0.18.4'
}

// 실행 모듈: Spring Boot 플러그인 적용 → bootJar 생성
apply plugin: 'org.springframework.boot'

bootJar {
	enabled = true
}
jar {
	enabled = false
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

dependencies {
	implementation project(':smite-core')
	implementation project(':smite-infra-redis')
	implementation project(':smite-matching')
	testImplementation testFixtures(project(':smite-infra-redis'))

	// Lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testCompileOnly 'org.projectlombok:lombok'
	testAnnotationProcessor 'org.projectlombok:lombok'

	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	implementation 'org.springframework.boot:spring-boot-starter-mail'

	runtimeOnly 'com.mysql:mysql-connector-j'

	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	runtimeOnly 'io.micrometer:micrometer-registry-prometheus'

	// Security & JWT
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
	implementation 'io.jsonwebtoken:jjwt-api:0.12.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.5'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.testcontainers:junit-jupiter'
	testImplementation 'com.redis:testcontainers-redis'
	testRuntimeOnly 'com.h2database:h2'

	// RestDocs & OpenAPI
	testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc'
	testImplementation 'com.epages:restdocs-api-spec-mockmvc:0.18.4'
	testImplementation 'io.rest-assured:spring-mock-mvc'

	// Swagger UI (WebJar)
	implementation 'org.webjars:swagger-ui:5.10.3'
	implementation 'org.webjars:webjars-locator-core'
}

openapi3 {
	setServer('http://localhost:8080')
	title = 'League of Smite API'
	description = 'League of Smite API 명세서'
	version = '1.0.0'
	format = 'yaml'
}

// 생성된 openapi3.yaml 파일을 정적 리소스 경로로 복사
tasks.register('copyOasToSwagger', Copy) {
	dependsOn 'openapi3'
	from 'build/api-spec/openapi3.yaml'
	into 'src/main/resources/static/docs'
}

// 빌드 시 문서도 최신화되도록 설정
bootJar {
	dependsOn 'copyOasToSwagger'
}
