export const ROUTE_PATHS = {
  home: '/',
  login: '/login',
  signup: '/signup',
  passwordReset: '/password/reset',
  oauth2Redirect: '/oauth2/redirect',
  match: '/match',
  profile: '/profile',
  customRooms: '/custom-games/rooms',
  customRoom: '/custom-games/rooms/:roomId',
  customRoomInvite: '/custom-games/join/:inviteCode',
  gameWaiting: '/game/:gameRoomId/waiting',
  gamePlay: '/game/:gameRoomId/play',
  gameResult: '/game/:gameRoomId/result',
} as const

export const ROUTE_NAMES = {
  home: 'home',
  login: 'login',
  signup: 'signup',
  passwordReset: 'password-reset',
  oauth2Redirect: 'oauth2-redirect',
  match: 'match',
  profile: 'profile',
  customRooms: 'custom-rooms',
  customRoom: 'custom-room',
  customRoomInvite: 'custom-room-invite',
  gameWaiting: 'game-waiting',
  gamePlay: 'game-play',
  gameResult: 'game-result',
} as const
